### ISSUE TITLE
Re-analysis of samples

### ISSUE THREAD

**Issue by mihuber** [ozagordi/VirMet#24]
To re-analyse a sample (because of stoppen pipeline, new version), the output folder of that sample should first be deleted manually. The pipeline should skip samples that already have an output folder.

**Comment by ozagordi** [comment]
Only viral blast should run again. An actual example of when and how this happened? What was the output?

**Comment by mihuber** [comment]
Not an issue anymore. To re-run a sample or a run, rename it and start the pipeline again.
