### ISSUE TITLE
Version of VirMet and virus reference database

### ISSUE THREAD

**Issue by mihuber** [ozagordi/VirMet#26]
It would be good if one could easily retrieve the version of MinVar and the last update date of the virus reference database (e.g. with a --version subcommand).

This would be important for

citation in publications
follow-up of changes in virus taxonomy

**Comment by ozagordi** [comment]
It is already possible to have information on the viral database like

```
timavo:~ blastdbcmd -db /data/virmet_databases/viral_nuccore/viral_db -info
Database: Viral database indexed 2017-04-18
	57,481 sequences; 1,194,074,656 total bases

Date: Apr 18, 2017  7:58 AM	Longest sequence: 2,473,870 bases

Volumes:
	/data/virmet_databases/viral_nuccore/viral_db
```

What else? Where should this information and the version go?

**Comment by mihuber** [comment]
Ok, but how do we know, with which version of the database a specific run/sample was analysed? Is the info on the database in a log file? Or do you keep track when the database is updated, so one could connect sample analysis date with the version of the database?

**Comment by mihuber** [comment]
I would make it on the sample level, because somebody could re-run only one sample of a run with an updated database. You could just write `blastdbcmd -db /data/virmet_databases/viral_nuccore/viral_db -info` into `sample_info.txt` for every sample.
