### ISSUE TITLE
Build database virus 

### ISSUE THREAD

**Issue by Castell34** [ozagordi/VirMet#29]
I try to build the database with the subcommand fetch, I obtained the next problem:

Traceback (most recent call last):
  File "./virmet", line 11, in <module>
    load_entry_point('VirMet==1.1.1', 'console_scripts', 'virmet')()
  File "/home/sonia/anaconda3/lib/python3.6/site-packages/virmet/__main__.py", line 120, in main
    args.func(args)
  File "/home/sonia/anaconda3/lib/python3.6/site-packages/virmet/__main__.py", line 44, in fetch_db
    fetch.main(args)
  File "/home/sonia/anaconda3/lib/python3.6/site-packages/virmet/fetch.py", line 21, in main
    cml_search = viral_query('n')
  File "/home/sonia/anaconda3/lib/python3.6/site-packages/virmet/common.py", line 134, in viral_query
    os.mkdir(target_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/data/virmet_databases/viral_nuccore'

could you tell me which the mistake in the build of database? please

**Comment by ozagordi** [comment]
Hi!
Sorry for the late reply. It stops when it tries to create the directory `/data/virmet_databases/viral_nuccore`. At this point it expects the directory `/data/virmet_databases` to be present. Do you have it? Can you make a directory there by giving `mkdir /data/virmet_databases/viral_nuccore`?

**Comment by Castell34** [comment]
Hi!

Do not worry thanks for your anwser, but  I already created the directory
and I try to run this command inside the directory and continues with the
error,


hugo@cidc-hugo:~/Desktop/VirMet-1.1.1/data/virmet_databases/viral_nuccore$
/home/hugo/Desktop/VirMet-1.1.1/bin/virmet fetch --viral n
Traceback (most recent call last):
  File "/home/hugo/Desktop/VirMet-1.1.1/bin/virmet", line 12, in <module>
    __main__.main()
  File "/home/hugo/Desktop/VirMet-1.1.1/virmet/__main__.py", line 120, in
main
    args.func(args)
  File "/home/hugo/Desktop/VirMet-1.1.1/virmet/__main__.py", line 44, in
fetch_db
    fetch.main(args)
  File "/home/hugo/Desktop/VirMet-1.1.1/virmet/fetch.py", line 21, in main
    cml_search = viral_query('n')
  File "/home/hugo/Desktop/VirMet-1.1.1/virmet/common.py", line 134, in
viral_query
    os.mkdir(target_dir)
FileNotFoundError: [Errno 2] No such file or directory:
'/data/virmet_databases/viral_nuccore'



And within the directory creates a file with the following:

INFO 2017/10/03 10:27:10 __main__.py: main() 116:
/home/hugo/Desktop/VirMet-1.1.1/bin/virmet fetch --viral n
INFO 2017/10/03 10:28:03 fetch.py: main() 16:     now in fetch_data
INFO 2017/10/03 10:28:03 fetch.py: main() 19:     downloading viral nuccore
sequences

I hope you can help me

Best regards

Hugo Castelán
Universidad Autónoma del Estado de Morelos




2017-10-03 8:49 GMT-05:00 Osvaldo Zagordi <notifications@github.com>:

**Comment by ozagordi** [comment]
What I see is that you created a directory called `/data/virmet_databases/` inside VirMet-1.1.1 inside your Desktop. That's not what is expected. The default location of the databases is `/data/virmet_databases`. In other words, `/data/virmet_databases` must be right at the root mount point (`/`). Once that exists, running fetch from anywhere in the system should start populate it.

**Comment by staltor** [comment]
Hi,

today I have built the viral DB  with the command   "fetch"

 ~/VirMet$ virmet fetch --viral n
Traceback (most recent call last):
  File "/home/miniconda2/envs/virmet1/bin/virmet", line 11, in <module>
    load_entry_point('VirMet==1.1.1', 'console_scripts', 'virmet')()
  File "/home/miniconda2/envs/virmet1/lib/python3.5/site-packages/virmet/__main__.py", line 120, in main
    args.func(args)
  File "/home/miniconda2/envs/virmet1/lib/python3.5/site-packages/virmet/__main__.py", line 44, in fetch_db
    fetch.main(args)
  File "/home/miniconda2/envs/virmet1/lib/python3.5/site-packages/virmet/fetch.py", line 42, in main
    assert accs_1 == accs_2, accs_1 ^ accs_2
AssertionError: {'NC_018086', 'JX982222', 'KC119188', 'JX982227', 'KC119187', 'JX507215', 'JX507213', 'JX982224', 'KC119184', 'KC119189', 'JX982220', 'JX507214', 'JX982225', 'KC113518', 'KC222955', 'JX682576', 'KC113517', 'AY823991', 'KC119186', 'JX982228', 'KC119185', 'NC_003629', 'JX982219', 'JX982221', 'JX982223', 'NC_014092', 'JX826607', 'JX982226'}

In the directory **/data/virmet_databases/viral_nuccore** I have
grep -c \> viral_database.fasta
62824
wc -l viral_seqs_info.tsv
62852 viral_seqs_info.tsv
wc -l viral_accn_taxid.dmp
62852 viral_accn_taxid.dmp 

Can I index my viral DB?


Best regards

**Comment by ozagordi** [comment]
Hi.
You should be able to index, but for some reason the sequences that were reported in the error message won’t be in your db (NC_018086, for example, is a phage). Please try updating it first (virmet update) and let me know. I will be able to give a closer look next week, though.

**Comment by staltor** [comment]
Hi,

~/VirMet$ virmet update --viral n

grep -c \> viral_database.fasta
62852
wc -l viral_seqs_info.tsv
62852 viral_seqs_info.tsv
wc -l viral_accn_taxid.dmp
62852 viral_accn_taxid.dmp

virmet index --viral n

thanks

**Comment by SantosJGND** [comment]
hi,

Sorry to reopen this. i got around this issue by manually changing DB_DIR in the common.py script to a directory that made sense to me. id go as far as passing the db_dir to a fetch argument in the main.py script since i want to automate this later. But its useless if a snake pipeline re-installs the  conda env. could i ask for the database directory to become an optional argument? frankly its a bit weird that it isnt (comparing to other software). and especially that it'd go to root. Thank you, Joao
