### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by mihuber** [ozagordi/VirMet#4]
- [x] tidy data format: table with columns run, sample_id, sample_name, quality, organism_category, species, reads, percent instead of separate stats.csv and orgs_list.csv
- [ ] coverage plot

**Comment by ozagordi** [comment]
What is really needed?
Now there are two files,  `stats.tsv`

| type        | read_count |
|----------------------|------|
| raw_reads            | 6250 |
| trimmed_long         | 5788 |
| high_quality         | 3883 |
| matching_humanGRCh38 | 3463 |
| matching_bact1       | 1    |
| matching_bact2       | 1    |
| matching_bact3       | 1    |
| matching_fungi1      | 1    |
| matching_bt_ref      | 1    |
| blasted_reads        | 420  |
| blast_hits           | 259  |
| viral_good_reads     | 257  |
| unknown_reads        | 163  |

and `orgs_list.tv`

| organism                        | reads |
|---------------------------------|-------|
| Human adenovirus 7              | 126   |
| Human poliovirus 1 strain Sabin | 45    |
| Human poliovirus 1 Mahoney      | 29    |
| Human adenovirus 3+11p          | 19    |
| Human adenovirus 50             | 12    |
| Human adenovirus B              | 8     |
| Human immunodeficiency virus 1  | 6     |
| Human poliovirus 1              | 4     |
| Human herpesvirus 5             | 2     |
| Human adenovirus 3              | 2     |
| Human poliovirus 2              | 1     |
| Human herpesvirus 4             | 1     |
| Human adenovirus 21             | 1     |
| Human adenovirus 16             | 1     |

Is this good?

**Comment by ozagordi** [comment]
Now they are as follows. Good?

| type | read_count |
|----------------------|------|
| raw_reads            | 6250 |
| trimmed_too_short    | 462  |
| low_entropy          | 1905 |
| passing_filter       | 3883 |
| matching_humanGRCh38 | 3463 |
| matching_bact1       | 1    |
| matching_bact2       | 1    |
| matching_bact3       | 1    |
| matching_fungi1      | 1    |
| matching_bt_ref      | 1    |
| reads_to_blast       | 420  |
| viral_reads          | 257  |
| undetermined_reads   | 163  |
